In [4]:
import numpy as np

In [3]:
4 + 2

6

In [8]:
x_data = np.linspace(1, 15, 15)

In [24]:
x_data

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [14]:
y_data = np.array([(lambda i: i ** 2 + 4)(x) for x in x_data])

In [15]:
y_data


array([  5.,   8.,  13.,  20.,  29.,  40.,  53.,  68.,  85., 104., 125.,
       148., 173., 200., 229.])

In [23]:
x_data[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.]])

In [27]:
pairs = np.stack([x_data, y_data], axis=1)

In [28]:
for x, y in pairs:
    print(x, y)

1.0 5.0
2.0 8.0
3.0 13.0
4.0 20.0
5.0 29.0
6.0 40.0
7.0 53.0
8.0 68.0
9.0 85.0
10.0 104.0
11.0 125.0
12.0 148.0
13.0 173.0
14.0 200.0
15.0 229.0
